<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Content-Language" content="en-us" />
<meta name="robots" content="all" />
<meta http-equiv="imagetoolbar" content="false" />
<meta name="MSSmartTagsPreventParsing" content="true" />
<link rel="Shortcut Icon" href="/favicon.ico" type="image/x-icon" />
<meta name="description" content="Patriot Pipes -  Loud when you want... Quiet when you need" />
<meta name="keywords" content="Harley Exhaust, Patriot Pipes, Patriot Defenders, Softtail Pipes, Touring, Dyna, Electra Glide, Street Glide,  Ultra Classic, Road King, Road Glide, Bad Boy, Heritage, Cross Bones, Fat Boy, Springer, Deluxe, Night Train, Motorcycle Exhaust, Motorcycle Pipes, Fuel Controller, Top Fueler" />
